import { getCodeDateKey } from "@/lib/dailyCode";

const VERSES = [
  { ref: "Psalm 1:1", text: "Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners, nor sitteth in the seat of the scornful." },
  { ref: "Psalm 1:2", text: "But his delight is in the law of the Lord; and in his law doth he meditate day and night." },
  { ref: "Psalm 1:3", text: "And he shall be like a tree planted by the rivers of water, that bringeth forth his fruit in his season; his leaf also shall not wither; and whatsoever he doeth shall prosper." },
  { ref: "Psalm 4:8", text: "I will both lay me down in peace, and sleep: for thou, Lord, only makest me dwell in safety." },
  { ref: "Psalm 5:3", text: "My voice shalt thou hear in the morning, O Lord; in the morning will I direct my prayer unto thee, and will look up." },
  { ref: "Psalm 9:9", text: "The Lord also will be a refuge for the oppressed, a refuge in times of trouble." },
  { ref: "Psalm 16:8", text: "I have set the Lord always before me: because he is at my right hand, I shall not be moved." },
  { ref: "Psalm 16:11", text: "Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore." },
  { ref: "Psalm 18:2", text: "The Lord is my rock, and my fortress, and my deliverer; my God, my strength, in whom I will trust." },
  { ref: "Psalm 18:30", text: "As for God, his way is perfect: the word of the Lord is tried: he is a buckler to all those that trust in him." },
  { ref: "Psalm 19:14", text: "Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O Lord, my strength, and my redeemer." },
  { ref: "Psalm 23:1", text: "The Lord is my shepherd; I shall not want." },
  { ref: "Psalm 23:3", text: "He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake." },
  { ref: "Psalm 23:4", text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me." },
  { ref: "Psalm 23:6", text: "Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the Lord for ever." },
  { ref: "Psalm 25:4", text: "Shew me thy ways, O Lord; teach me thy paths." },
  { ref: "Psalm 25:5", text: "Lead me in thy truth, and teach me: for thou art the God of my salvation; on thee do I wait all the day." },
  { ref: "Psalm 27:1", text: "The Lord is my light and my salvation; whom shall I fear? the Lord is the strength of my life; of whom shall I be afraid?" },
  { ref: "Psalm 27:14", text: "Wait on the Lord: be of good courage, and he shall strengthen thine heart: wait, I say, on the Lord." },
  { ref: "Psalm 28:7", text: "The Lord is my strength and my shield; my heart trusted in him, and I am helped." },
  { ref: "Psalm 29:11", text: "The Lord will give strength unto his people; the Lord will bless his people with peace." },
  { ref: "Psalm 31:24", text: "Be of good courage, and he shall strengthen your heart, all ye that hope in the Lord." },
  { ref: "Psalm 32:8", text: "I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye." },
  { ref: "Psalm 34:4", text: "I sought the Lord, and he heard me, and delivered me from all my fears." },
  { ref: "Psalm 34:8", text: "O taste and see that the Lord is good: blessed is the man that trusteth in him." },
  { ref: "Psalm 34:18", text: "The Lord is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit." },
  { ref: "Psalm 37:3", text: "Trust in the Lord, and do good; so shalt thou dwell in the land, and verily thou shalt be fed." },
  { ref: "Psalm 37:4", text: "Delight thyself also in the Lord; and he shall give thee the desires of thine heart." },
  { ref: "Psalm 37:5", text: "Commit thy way unto the Lord; trust also in him; and he shall bring it to pass." },
  { ref: "Psalm 37:7", text: "Rest in the Lord, and wait patiently for him." },
  { ref: "Psalm 37:23", text: "The steps of a good man are ordered by the Lord: and he delighteth in his way." },
  { ref: "Psalm 37:39", text: "But the salvation of the righteous is of the Lord: he is their strength in the time of trouble." },
  { ref: "Psalm 40:1", text: "I waited patiently for the Lord; and he inclined unto me, and heard my cry." },
  { ref: "Psalm 40:8", text: "I delight to do thy will, O my God: yea, thy law is within my heart." },
  { ref: "Psalm 42:11", text: "Why art thou cast down, O my soul? and why art thou disquieted within me? hope thou in God." },
  { ref: "Psalm 46:1", text: "God is our refuge and strength, a very present help in trouble." },
  { ref: "Psalm 46:10", text: "Be still, and know that I am God." },
  { ref: "Psalm 48:14", text: "For this God is our God for ever and ever: he will be our guide even unto death." },
  { ref: "Psalm 50:15", text: "And call upon me in the day of trouble: I will deliver thee, and thou shalt glorify me." },
  { ref: "Psalm 51:10", text: "Create in me a clean heart, O God; and renew a right spirit within me." },
  { ref: "Psalm 55:22", text: "Cast thy burden upon the Lord, and he shall sustain thee: he shall never suffer the righteous to be moved." },
  { ref: "Psalm 56:3", text: "What time I am afraid, I will trust in thee." },
  { ref: "Psalm 57:2", text: "I will cry unto God most high; unto God that performeth all things for me." },
  { ref: "Psalm 61:2", text: "From the end of the earth will I cry unto thee, when my heart is overwhelmed: lead me to the rock that is higher than I." },
  { ref: "Psalm 62:1", text: "Truly my soul waiteth upon God: from him cometh my salvation." },
  { ref: "Psalm 62:5", text: "My soul, wait thou only upon God; for my expectation is from him." },
  { ref: "Psalm 62:8", text: "Trust in him at all times; ye people, pour out your heart before him: God is a refuge for us." },
  { ref: "Psalm 63:1", text: "O God, thou art my God; early will I seek thee: my soul thirsteth for thee." },
  { ref: "Psalm 66:20", text: "Blessed be God, which hath not turned away my prayer, nor his mercy from me." },
  { ref: "Psalm 68:19", text: "Blessed be the Lord, who daily loadeth us with benefits, even the God of our salvation." },
  { ref: "Psalm 73:26", text: "My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever." },
  { ref: "Psalm 84:11", text: "For the Lord God is a sun and shield: the Lord will give grace and glory: no good thing will he withhold from them that walk uprightly." },
  { ref: "Psalm 86:11", text: "Teach me thy way, O Lord; I will walk in thy truth: unite my heart to fear thy name." },
  { ref: "Psalm 90:12", text: "So teach us to number our days, that we may apply our hearts unto wisdom." },
  { ref: "Psalm 91:1", text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty." },
  { ref: "Psalm 91:2", text: "I will say of the Lord, He is my refuge and my fortress: my God; in him will I trust." },
  { ref: "Psalm 91:11", text: "For he shall give his angels charge over thee, to keep thee in all thy ways." },
  { ref: "Psalm 91:14", text: "Because he hath set his love upon me, therefore will I deliver him: I will set him on high, because he hath known my name." },
  { ref: "Psalm 94:19", text: "In the multitude of my thoughts within me thy comforts delight my soul." },
  { ref: "Psalm 95:6", text: "O come, let us worship and bow down: let us kneel before the Lord our maker." },
  { ref: "Psalm 100:4", text: "Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name." },
  { ref: "Psalm 103:2", text: "Bless the Lord, O my soul, and forget not all his benefits." },
  { ref: "Psalm 103:3", text: "Who forgiveth all thine iniquities; who healeth all thy diseases." },
  { ref: "Psalm 103:12", text: "As far as the east is from the west, so far hath he removed our transgressions from us." },
  { ref: "Psalm 107:1", text: "O give thanks unto the Lord, for he is good: for his mercy endureth for ever." },
  { ref: "Psalm 112:7", text: "He shall not be afraid of evil tidings: his heart is fixed, trusting in the Lord." },
  { ref: "Psalm 118:6", text: "The Lord is on my side; I will not fear: what can man do unto me?" },
  { ref: "Psalm 118:8", text: "It is better to trust in the Lord than to put confidence in man." },
  { ref: "Psalm 118:24", text: "This is the day which the Lord hath made; we will rejoice and be glad in it." },
  { ref: "Psalm 119:11", text: "Thy word have I hid in mine heart, that I might not sin against thee." },
  { ref: "Psalm 119:105", text: "Thy word is a lamp unto my feet, and a light unto my path." },
  { ref: "Psalm 121:1", text: "I will lift up mine eyes unto the hills, from whence cometh my help." },
  { ref: "Psalm 121:2", text: "My help cometh from the Lord, which made heaven and earth." },
  { ref: "Psalm 121:7", text: "The Lord shall preserve thee from all evil: he shall preserve thy soul." },
  { ref: "Psalm 125:1", text: "They that trust in the Lord shall be as mount Zion, which cannot be removed, but abideth for ever." },
  { ref: "Psalm 127:1", text: "Except the Lord build the house, they labour in vain that build it." },
  { ref: "Psalm 130:5", text: "I wait for the Lord, my soul doth wait, and in his word do I hope." },
  { ref: "Psalm 138:3", text: "In the day when I cried thou answeredst me, and strengthenedst me with strength in my soul." },
  { ref: "Psalm 138:8", text: "The Lord will perfect that which concerneth me: thy mercy, O Lord, endureth for ever." },
  { ref: "Psalm 139:23", text: "Search me, O God, and know my heart: try me, and know my thoughts." },
  { ref: "Psalm 141:3", text: "Set a watch, O Lord, before my mouth; keep the door of my lips." },
  { ref: "Psalm 143:8", text: "Cause me to hear thy lovingkindness in the morning; for in thee do I trust." },
  { ref: "Psalm 144:1", text: "Blessed be the Lord my strength, which teacheth my hands to war, and my fingers to fight." },
  { ref: "Psalm 145:18", text: "The Lord is nigh unto all them that call upon him, to all that call upon him in truth." },
  { ref: "Psalm 147:3", text: "He healeth the broken in heart, and bindeth up their wounds." },
  { ref: "Psalm 150:6", text: "Let every thing that hath breath praise the Lord. Praise ye the Lord." },
  { ref: "Proverbs 1:7", text: "The fear of the Lord is the beginning of knowledge: but fools despise wisdom and instruction." },
  { ref: "Proverbs 2:6", text: "For the Lord giveth wisdom: out of his mouth cometh knowledge and understanding." },
  { ref: "Proverbs 3:3", text: "Let not mercy and truth forsake thee: bind them about thy neck; write them upon the table of thine heart." },
  { ref: "Proverbs 3:5", text: "Trust in the Lord with all thine heart; and lean not unto thine own understanding." },
  { ref: "Proverbs 3:6", text: "In all thy ways acknowledge him, and he shall direct thy paths." },
  { ref: "Proverbs 3:7", text: "Be not wise in thine own eyes: fear the Lord, and depart from evil." },
  { ref: "Proverbs 3:9", text: "Honour the Lord with thy substance, and with the firstfruits of all thine increase." },
  { ref: "Proverbs 3:11", text: "My son, despise not the chastening of the Lord; neither be weary of his correction." },
  { ref: "Proverbs 3:26", text: "For the Lord shall be thy confidence, and shall keep thy foot from being taken." },
  { ref: "Proverbs 4:7", text: "Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding." },
  { ref: "Proverbs 4:23", text: "Keep thy heart with all diligence; for out of it are the issues of life." },
  { ref: "Proverbs 4:26", text: "Ponder the path of thy feet, and let all thy ways be established." },
  { ref: "Proverbs 10:12", text: "Hatred stirreth up strifes: but love covereth all sins." },
  { ref: "Proverbs 10:22", text: "The blessing of the Lord, it maketh rich, and he addeth no sorrow with it." },
  { ref: "Proverbs 11:2", text: "When pride cometh, then cometh shame: but with the lowly is wisdom." },
  { ref: "Proverbs 11:14", text: "Where no counsel is, the people fall: but in the multitude of counsellors there is safety." },
  { ref: "Proverbs 12:25", text: "Heaviness in the heart of man maketh it stoop: but a good word maketh it glad." },
  { ref: "Proverbs 14:12", text: "There is a way which seemeth right unto a man, but the end thereof are the ways of death." },
  { ref: "Proverbs 15:1", text: "A soft answer turneth away wrath: but grievous words stir up anger." },
  { ref: "Proverbs 15:3", text: "The eyes of the Lord are in every place, beholding the evil and the good." },
  { ref: "Proverbs 16:3", text: "Commit thy works unto the Lord, and thy thoughts shall be established." },
  { ref: "Proverbs 16:7", text: "When a man's ways please the Lord, he maketh even his enemies to be at peace with him." },
  { ref: "Proverbs 16:9", text: "A man's heart deviseth his way: but the Lord directeth his steps." },
  { ref: "Proverbs 16:20", text: "He that handleth a matter wisely shall find good: and whoso trusteth in the Lord, happy is he." },
  { ref: "Proverbs 17:17", text: "A friend loveth at all times, and a brother is born for adversity." },
  { ref: "Proverbs 18:10", text: "The name of the Lord is a strong tower: the righteous runneth into it, and is safe." },
  { ref: "Proverbs 18:21", text: "Death and life are in the power of the tongue: and they that love it shall eat the fruit thereof." },
  { ref: "Proverbs 19:21", text: "There are many devices in a man's heart; nevertheless the counsel of the Lord, that shall stand." },
  { ref: "Proverbs 22:1", text: "A good name is rather to be chosen than great riches, and loving favour rather than silver and gold." },
  { ref: "Proverbs 22:6", text: "Train up a child in the way he should go: and when he is old, he will not depart from it." },
  { ref: "Proverbs 27:17", text: "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend." },
  { ref: "Proverbs 28:13", text: "He that covereth his sins shall not prosper: but whoso confesseth and forsaketh them shall have mercy." },
  { ref: "Proverbs 29:25", text: "The fear of man bringeth a snare: but whoso putteth his trust in the Lord shall be safe." },
  { ref: "Proverbs 30:5", text: "Every word of God is pure: he is a shield unto them that put their trust in him." },
  { ref: "Proverbs 31:8", text: "Open thy mouth for the dumb in the cause of all such as are appointed to destruction." },
  { ref: "Proverbs 31:30", text: "Favour is deceitful, and beauty is vain: but a woman that feareth the Lord, she shall be praised." },
];

function getDayIndex(date = new Date()) {
  const dateKey = getCodeDateKey(date);
  let hash = 0;
  for (let i = 0; i < dateKey.length; i++) {
    hash = ((hash << 5) - hash) + dateKey.charCodeAt(i);
    hash |= 0;
  }
  return Math.abs(hash) % VERSES.length;
}

export function getDailyVerse(date = new Date()) {
  return VERSES[getDayIndex(date)];
}
